### ISSUE TITLE
Paired characters won't wrap

### ISSUE THREAD

**Issue by novoid** [mrkkrp/char-menu#1]
Hi!

I lied :-)

Paired characters from your example do work:

```
"‘’" "“”" "…" "«»"
```

However, when I define `"»«"` (German language style), select a text region, apply your beautiful function, the region doesn't get wrapped.

My whole char-menu configuration (Emacs 24.4.1; using `use-package`) is:

```
(use-package char-menu
  :ensure t
  :defer 10
  :config
  (setq char-menu
        '("—" "‘’" "“”" "…" "«»" "»«" "–" "∅" "š" "•" "©" "†" "°" "·" "§" "№" "★"
         ("Arrows"     "←" "→" "↑" "↓" "⇐" "⇒" "⇑" "⇓")
         ("Math"       "≈" "≡" "≠" "∞" "×" "±" "∓" "÷" "√")
         ("Greek"      "α" "β" "Y" "δ" "ε" "ζ" "η" "θ" "ι" "κ" "λ" "μ"
          "ν" "ξ" "ο" "π" "ρ" "σ" "τ" "υ" "φ" "χ" "ψ" "ω")
         ("Hatschek"   "Ǎ" "ǎ" "Č" "č" "Ď" "ď" "Ě" "ě" "Ǧ" "ǧ" "Ȟ" "ȟ"
          "Ǐ" "ǐ" "ǰ" "Ǩ" "ǩ" "Ľ" "ľ" "Ň" "ň" "Ǒ" "ǒ" "Ř" "ř" "Š" "š" "Ť" "ť"
          "Ǔ" "ǔ" "Ǚ" "ǚ" "Ž" "ž" "Ǯ" "ǯ")
        ))
  (global-set-key [f7] 'char-menu)
)
```

**Comment by mrkkrp** [comment]
For your pair to be recognized, it should consist of two characters where the first should have Unicode category `Punctuation, Initial quote` and the second `Punctuation, Final quote`. When I was designing this, I knew that some European languages use this style of quoting (and even `»»`), but I was under the impression that there should be different characters for this in Unicode (so in each case the actual opening quote will be `Punctuation, Initial quote`). Now I see that it is not the case, the same “guillemet” characters are used everywhere.

It is easy to fix, though, I will push necessary changes soon.

**Comment by mrkkrp** [comment]
Should be fixed now.

**Comment by novoid** [comment]
I did not know about Unicode categories :-O

I just copied the `«»` and switched their position. Maybe there are different guillemet characters for the German quoting style - I did not look into it.

Thanks for fixing it. I hope it will be available via ELPA soon. Greetings from Graz/Austria!
